name: generate-help

on: [push]

jobs:
  docs:
    runs-on: ubuntu-latest
    name: pandoc to vimdoc
    steps:
      - uses: actions/checkout@v2
      - name: panvimdoc
        uses: kdheepak/panvimdoc@main
        with:
          vimdoc: help-nvim-agenda.txt
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Auto-generate help documentation"
          branch: ${{ github.head_ref }}
