name: generate-help

on: [push]

permissions: write-all

jobs:
  docs:
    runs-on: ubuntu-latest
    name: generate-help-file-from-readme
    steps:
      - uses: actions/checkout@v2
      - name: panvimdoc
        uses: kdheepak/panvimdoc@main
        with:
          vimdoc: help
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Agenda.GitHubBot: auto-generate help documentation"
          branch: ${{ github.head_ref }}
